From Atıl Samancıoğlu's Course : Data Science and Machine Learning 

-> Pandas Library 🐼

Jay Alammar Web Link : https://jalammar.github.io/gentle-visual-intro-to-data-analysis-python-pandas/

In [1]:
import numpy as np
import pandas as pd

In [2]:
grades = {"Atıl" : 50 , "James" : 60, "Lars" : 30}

In [3]:
pd.Series(grades)

Atıl     50
James    60
Lars     30
dtype: int64

In [4]:
names = ["Atıl", "James", "Lars"]
grades = [50, 60, 30]

In [5]:
pd.Series(names)

0     Atıl
1    James
2     Lars
dtype: object

In [6]:
pd.Series(grades)

0    50
1    60
2    30
dtype: int64

In [7]:
pd.Series(grades, names)

Atıl     50
James    60
Lars     30
dtype: int64

In [8]:
pd.Series(data = grades, index = names)

Atıl     50
James    60
Lars     30
dtype: int64

Pandas With NumPy

In [9]:
numpy_array = np.array([50, 40, 30, 20])

In [10]:
pd.Series(numpy_array)

0    50
1    40
2    30
3    20
dtype: int64

Arithmetic

In [11]:
contest_result = pd.Series(data = [10,5,100], index = ["Atıl", "James", "Lars"])
contest_result2 = pd.Series(data = [20,50,10], index = ["Atıl", "James", "Lars"])

In [12]:
contest_result

Atıl      10
James      5
Lars     100
dtype: int64

In [13]:
contest_result["Atıl"]

np.int64(10)

In [14]:
contest_result2["James"]

np.int64(50)

In [15]:
final_result = contest_result + contest_result2
final_result

Atıl      30
James     55
Lars     110
dtype: int64

In [16]:
contest_result - contest_result2

Atıl    -10
James   -45
Lars     90
dtype: int64

In [17]:
contest_result * contest_result2

Atıl      200
James     250
Lars     1000
dtype: int64

In [18]:
contest_result / contest_result2

Atıl      0.5
James     0.1
Lars     10.0
dtype: float64

In [19]:
contest_result ** contest_result2

Atıl     7766279631452241920
James   -6776596920136667815
Lars     7766279631452241920
dtype: int64

In [20]:
contest_result // contest_result2

Atıl      0
James     0
Lars     10
dtype: int64

In [21]:
different_series = pd.Series([20,30,40,50],["a","b","c","d"])

In [22]:
different_series2 = pd.Series([10,5,3,1],["a","c","f","g"])

In [23]:
different_series + different_series2

a    30.0
b     NaN
c    45.0
d     NaN
f     NaN
g     NaN
dtype: float64

Introduction to DataFrame

In [24]:
import numpy as np
import pandas as pd

In [25]:
data = np.random.randn(4,3)

In [26]:
data

array([[ 0.01926399,  0.41443356, -1.38209381],
       [ 0.34782989, -0.99541701, -0.16035713],
       [ 0.69740573,  0.16033916,  0.84904143],
       [-1.24813221,  0.05407541,  1.02473517]])

In [27]:
data_frame = pd.DataFrame(data)
data_frame

          0         1         2
0  0.019264  0.414434 -1.382094
1  0.347830 -0.995417 -0.160357
2  0.697406  0.160339  0.849041
3 -1.248132  0.054075  1.024735

In [28]:
type(data_frame)

pandas.core.frame.DataFrame

In [29]:
data_frame[0]

0    0.019264
1    0.347830
2    0.697406
3   -1.248132
Name: 0, dtype: float64

In [30]:
type(data_frame[0])

pandas.core.series.Series

In [31]:
new_df = pd.DataFrame(data, index = ["Atil","Zeynep","Atlas","Mehmet"], columns = ["Salary", "Age", "Seniority"])
new_df

          Salary       Age  Seniority
Atil    0.019264  0.414434  -1.382094
Zeynep  0.347830 -0.995417  -0.160357
Atlas   0.697406  0.160339   0.849041
Mehmet -1.248132  0.054075   1.024735

In [32]:
new_df["Salary"]

Atil      0.019264
Zeynep    0.347830
Atlas     0.697406
Mehmet   -1.248132
Name: Salary, dtype: float64

In [33]:
new_df["Age"]

Atil      0.414434
Zeynep   -0.995417
Atlas     0.160339
Mehmet    0.054075
Name: Age, dtype: float64

In [34]:
new_df[["Age","Salary"]]

             Age    Salary
Atil    0.414434  0.019264
Zeynep -0.995417  0.347830
Atlas   0.160339  0.697406
Mehmet  0.054075 -1.248132

In [35]:
new_df.loc["Atil"]

Salary       0.019264
Age          0.414434
Seniority   -1.382094
Name: Atil, dtype: float64

In [36]:
new_df.iloc[0]

Salary       0.019264
Age          0.414434
Seniority   -1.382094
Name: Atil, dtype: float64

In [37]:
new_df

          Salary       Age  Seniority
Atil    0.019264  0.414434  -1.382094
Zeynep  0.347830 -0.995417  -0.160357
Atlas   0.697406  0.160339   0.849041
Mehmet -1.248132  0.054075   1.024735

In [38]:
new_df.iloc[:,2]

Atil     -1.382094
Zeynep   -0.160357
Atlas     0.849041
Mehmet    1.024735
Name: Seniority, dtype: float64

In [39]:
new_df["Age"]

Atil      0.414434
Zeynep   -0.995417
Atlas     0.160339
Mehmet    0.054075
Name: Age, dtype: float64

In [40]:
new_df["Extra"] = 10

In [41]:
new_df

          Salary       Age  Seniority  Extra
Atil    0.019264  0.414434  -1.382094     10
Zeynep  0.347830 -0.995417  -0.160357     10
Atlas   0.697406  0.160339   0.849041     10
Mehmet -1.248132  0.054075   1.024735     10

In [42]:
new_df.drop("Extra", axis = 1)

          Salary       Age  Seniority
Atil    0.019264  0.414434  -1.382094
Zeynep  0.347830 -0.995417  -0.160357
Atlas   0.697406  0.160339   0.849041
Mehmet -1.248132  0.054075   1.024735

In [43]:
new_df

          Salary       Age  Seniority  Extra
Atil    0.019264  0.414434  -1.382094     10
Zeynep  0.347830 -0.995417  -0.160357     10
Atlas   0.697406  0.160339   0.849041     10
Mehmet -1.248132  0.054075   1.024735     10

In [44]:
new_df = new_df.drop("Extra" , axis = 1)

In [45]:
new_df

          Salary       Age  Seniority
Atil    0.019264  0.414434  -1.382094
Zeynep  0.347830 -0.995417  -0.160357
Atlas   0.697406  0.160339   0.849041
Mehmet -1.248132  0.054075   1.024735

In [46]:
new_df["Extra"] = 10

In [47]:
new_df

          Salary       Age  Seniority  Extra
Atil    0.019264  0.414434  -1.382094     10
Zeynep  0.347830 -0.995417  -0.160357     10
Atlas   0.697406  0.160339   0.849041     10
Mehmet -1.248132  0.054075   1.024735     10

In [48]:
new_df.drop("Extra", axis = 1 , inplace = True)

In [49]:
new_df

          Salary       Age  Seniority
Atil    0.019264  0.414434  -1.382094
Zeynep  0.347830 -0.995417  -0.160357
Atlas   0.697406  0.160339   0.849041
Mehmet -1.248132  0.054075   1.024735

In [50]:
new_df

          Salary       Age  Seniority
Atil    0.019264  0.414434  -1.382094
Zeynep  0.347830 -0.995417  -0.160357
Atlas   0.697406  0.160339   0.849041
Mehmet -1.248132  0.054075   1.024735

In [51]:
new_df.drop("Mehmet", axis = 0)

          Salary       Age  Seniority
Atil    0.019264  0.414434  -1.382094
Zeynep  0.347830 -0.995417  -0.160357
Atlas   0.697406  0.160339   0.849041

In [52]:
new_df.loc["Atlas"]

Salary       0.697406
Age          0.160339
Seniority    0.849041
Name: Atlas, dtype: float64

In [53]:
new_df.loc["Atlas"]["Salary"]

np.float64(0.6974057338232509)

In [54]:
new_df.loc["Atlas","Salary"]

np.float64(0.6974057338232509)

In [55]:
new_df.loc["Atlas","Salary"] = 100

In [56]:
new_df

            Salary       Age  Seniority
Atil      0.019264  0.414434  -1.382094
Zeynep    0.347830 -0.995417  -0.160357
Atlas   100.000000  0.160339   0.849041
Mehmet   -1.248132  0.054075   1.024735

In [57]:
new_df > 0

        Salary    Age  Seniority
Atil      True   True      False
Zeynep    True  False      False
Atlas     True   True       True
Mehmet   False   True       True

In [58]:
boolean_frame = new_df > 0

In [59]:
boolean_frame

        Salary    Age  Seniority
Atil      True   True      False
Zeynep    True  False      False
Atlas     True   True       True
Mehmet   False   True       True

In [60]:
new_df[boolean_frame]

            Salary       Age  Seniority
Atil      0.019264  0.414434        NaN
Zeynep    0.347830       NaN        NaN
Atlas   100.000000  0.160339   0.849041
Mehmet         NaN  0.054075   1.024735

In [61]:
new_df[new_df > 0]

            Salary       Age  Seniority
Atil      0.019264  0.414434        NaN
Zeynep    0.347830       NaN        NaN
Atlas   100.000000  0.160339   0.849041
Mehmet         NaN  0.054075   1.024735

In [62]:
new_df[new_df["Salary"] > 1]

       Salary       Age  Seniority
Atlas   100.0  0.160339   0.849041

In [63]:
new_df[new_df["Age"] > 1]

Empty DataFrame
Columns: [Salary, Age, Seniority]
Index: []

DataFrame Index

In [64]:
new_df.reset_index()

    index      Salary       Age  Seniority
0    Atil    0.019264  0.414434  -1.382094
1  Zeynep    0.347830 -0.995417  -0.160357
2   Atlas  100.000000  0.160339   0.849041
3  Mehmet   -1.248132  0.054075   1.024735

In [65]:
reset_frame = new_df.reset_index()

In [66]:
reset_frame

    index      Salary       Age  Seniority
0    Atil    0.019264  0.414434  -1.382094
1  Zeynep    0.347830 -0.995417  -0.160357
2   Atlas  100.000000  0.160339   0.849041
3  Mehmet   -1.248132  0.054075   1.024735

In [67]:
new_indices = ["Ati","Zey","Atl","Meh"]

In [68]:
new_df["NewIndex"] = new_indices

In [69]:
new_df

            Salary       Age  Seniority NewIndex
Atil      0.019264  0.414434  -1.382094      Ati
Zeynep    0.347830 -0.995417  -0.160357      Zey
Atlas   100.000000  0.160339   0.849041      Atl
Mehmet   -1.248132  0.054075   1.024735      Meh

In [70]:
new_df.set_index("NewIndex", inplace = True)

In [71]:
new_df

              Salary       Age  Seniority
NewIndex
Ati         0.019264  0.414434  -1.382094
Zey         0.347830 -0.995417  -0.160357
Atl       100.000000  0.160339   0.849041
Meh        -1.248132  0.054075   1.024735

Multi Index

In [72]:
first_index = ["Simpson","Simpson","Simpson","South Park", "South Park","South Park"]

In [73]:
inner_index = ["Homer","Bart","Marge","Cartman","Kenny","Kyle"]

In [74]:
zipped_index = list(zip(first_index,inner_index))

In [75]:
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [76]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [77]:
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [78]:
sample_values = np.ones((6,2))

In [79]:
big_df = pd.DataFrame(sample_values, index = zipped_index , columns = ["Age", "Salary"] )

In [80]:
big_df

                    Age  Salary
Simpson    Homer    1.0     1.0
           Bart     1.0     1.0
           Marge    1.0     1.0
South Park Cartman  1.0     1.0
           Kenny    1.0     1.0
           Kyle     1.0     1.0

This file ended, keep going with part 2...